server:
  port: ${server_port}
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.11.135:8848
        namespace: a01229f6-fcfb-4dfd-ae9f-ca293ddcbbf6
        group: dev
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mynote-system
          uri: lb://mynote-system
          predicates:
            - Path=/sys/**
        - id: mynote-note
          uri: lb://mynote-note
          predicates:
            - Path=/note/**
        - id: mynote-blog
          uri: lb://mynote-blog
          predicates:
            - Path=/blog/**
        - id: mynote-third-party
          uri: lb://mynote-third-party
          predicates:
            - Path=/third/party/**



logging:
  config: classpath:log4j2-dev.xml

server_port: ${SERVER_PORT:8200}